<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>RNG</AssemblyName>
    <AssemblyVersion>2.0.0</AssemblyVersion>
    <Version>2.0.0</Version>
  </PropertyGroup>

  <Import Project="..\Shared\Orias_RNG_Class\Orias_RNG_Class.projitems" Label="Shared" />

</Project>
